import{a as B,S as R,i as a}from"./assets/vendor-BclIaOog.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&i(f)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();const q="https://pixabay.com/api/",I="42479769-783ae4e586acc6dbf443741d9",S=15;async function h(t,o=1){const e={key:I,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:o};try{return(await B.get(q,{params:e})).data}catch(i){throw console.error("Error fetching images:",i),i}}const y=document.querySelector(".gallery"),l=document.getElementById("top-loader"),c=document.getElementById("bottom-loader"),u=document.querySelector(".load-more"),M=new R(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const o=t.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="photo-card">
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",o),M.refresh()}function $(){y.innerHTML=""}function L(t="top"){t==="top"?l&&(l.classList.remove("is-hidden"),l.classList.add("is-visible")):c&&(c.classList.remove("is-hidden"),c.classList.add("is-visible"),u.classList.add("is-hidden"))}function b(t="top"){t==="top"?l&&(l.classList.add("is-hidden"),l.classList.remove("is-visible")):c&&(c.classList.add("is-hidden"),c.classList.remove("is-visible"),u.classList.remove("is-hidden"))}function v(){u&&u.classList.remove("is-hidden")}function d(){u&&u.classList.add("is-hidden")}function w(t){return new Promise(o=>setTimeout(o,t))}const E=document.getElementById("search-form"),A=E.querySelector('input[name="searchQuery"]'),O=document.querySelector(".load-more");document.getElementById("top-loader");document.getElementById("bottom-loader");let n=1,p="",m=0;const P=15;E.addEventListener("submit",async t=>{t.preventDefault();const o=A.value.trim();if(!o){a.warning({title:"Oops",message:"Please enter a search query!",position:"topRight"});return}p=o,n=1,m=0,$(),d(),L("top"),await new Promise(requestAnimationFrame);try{const[e]=await Promise.all([h(p,n),w(700)]);if(m=e.totalHits,e.hits.length===0){a.info({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"topRight"}),d();return}g(e.hits),Math.ceil(m/P)>n?v():(d(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{b("top")}});O.addEventListener("click",async()=>{const t=Math.ceil(m/P);if(n>=t){d(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}n+=1,L("bottom"),d(),await new Promise(requestAnimationFrame);try{const[o]=await Promise.all([h(p,n),w(700)]);g(o.hits),n>=t?(d(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v();const e=document.querySelector(".gallery li");if(e){const{height:i}=e.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}catch{a.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{b("bottom")}});
//# sourceMappingURL=index.js.map
