import{a as E,S as q,i as n}from"./assets/vendor-BclIaOog.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function e(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(o){if(o.ep)return;o.ep=!0;const s=e(o);fetch(o.href,s)}})();const B="https://pixabay.com/api/",R="42479769-783ae4e586acc6dbf443741d9",S=15;async function f(t,r=1){const e={key:R,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:r};try{return(await E.get(B,{params:e})).data}catch(i){throw console.error("Error fetching images:",i),i}}const h=document.querySelector(".gallery"),l=document.getElementById("top-loader"),c=document.getElementById("bottom-loader"),d=document.querySelector(".load-more"),I=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){const r=t.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="photo-card">
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",r),I.refresh()}function M(){h.innerHTML=""}function g(t="top"){t==="top"?(l.classList.remove("is-hidden"),l.classList.add("is-visible")):(c.classList.remove("is-hidden"),c.classList.add("is-visible"),d.classList.add("is-hidden"))}function L(t="top"){t==="top"?(l.classList.add("is-hidden"),l.classList.remove("is-visible")):(c.classList.add("is-hidden"),c.classList.remove("is-visible"),d.classList.remove("is-hidden"))}function b(){d.classList.remove("is-hidden")}function v(){d.classList.add("is-hidden")}function w(t){return new Promise(r=>setTimeout(r,t))}const P=document.getElementById("search-form"),$=P.querySelector('input[name="searchQuery"]'),A=document.querySelector(".load-more");let a=1,m="",p=0;P.addEventListener("submit",async t=>{t.preventDefault();const r=$.value.trim();if(!r){n.warning({title:"Oops",message:"Please enter a search query!",position:"topRight"});return}m=r,a=1,M(),v(),g("top"),await new Promise(requestAnimationFrame);try{const[e]=await Promise.all([f(m,a),w(700)]);p=e.totalHits,e.hits.length===0?n.info({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"topRight"}):(y(e.hits),p>a*15&&b())}catch{n.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{L("top")}});A.addEventListener("click",async()=>{a+=1,g("bottom"),v(),await new Promise(requestAnimationFrame);try{const[t]=await Promise.all([f(m,a),w(700)]);y(t.hits);const r=Math.ceil(p/15);a<r?b():n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});const e=document.querySelector(".gallery li");if(e){const{height:i}=e.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}catch{n.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{L("bottom")}});
//# sourceMappingURL=index.js.map
