import{a as P,S as B,i as d}from"./assets/vendor-BclIaOog.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&i(m)}).observe(document,{childList:!0,subtree:!0});function e(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(o){if(o.ep)return;o.ep=!0;const s=e(o);fetch(o.href,s)}})();const q="https://pixabay.com/api/",I="42479769-783ae4e586acc6dbf443741d9",R=15;async function p(t,r=1){const e={key:I,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:R,page:r};try{return(await P.get(q,{params:e})).data}catch(i){throw console.error("Error fetching images:",i),i}}const h=document.querySelector(".gallery"),a=document.getElementById("top-loader"),n=document.getElementById("bottom-loader"),c=document.querySelector(".load-more"),S=new B(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){const r=t.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="photo-card">
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",r),S.refresh()}function M(){h.innerHTML=""}function g(t="top"){t==="top"?a&&(a.classList.remove("is-hidden"),a.classList.add("is-visible")):n&&(n.classList.remove("is-hidden"),n.classList.add("is-visible"),c.classList.add("is-hidden"))}function L(t="top"){t==="top"?a&&(a.classList.add("is-hidden"),a.classList.remove("is-visible")):n&&(n.classList.add("is-hidden"),n.classList.remove("is-visible"),c.classList.remove("is-hidden"))}function b(){c&&c.classList.remove("is-hidden")}function v(){c&&c.classList.add("is-hidden")}function w(t){return new Promise(r=>setTimeout(r,t))}const E=document.getElementById("search-form"),$=E.querySelector('input[name="searchQuery"]'),A=document.querySelector(".load-more");document.getElementById("top-loader");document.getElementById("bottom-loader");let l=1,u="",f=0;E.addEventListener("submit",async t=>{t.preventDefault();const r=$.value.trim();if(!r){d.warning({title:"Oops",message:"Please enter a search query!",position:"topRight"});return}u=r,l=1,M(),v(),g("top"),await new Promise(requestAnimationFrame);try{const[e]=await Promise.all([p(u,l),w(700)]);f=e.totalHits,e.hits.length===0?d.info({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"topRight"}):(y(e.hits),f>l*15&&b())}catch{d.error({title:"Error",message:"Failed to fetch images. Try again later.",position:"topRight"})}finally{L("top")}});A.addEventListener("click",async()=>{l+=1,g("bottom"),v(),await new Promise(requestAnimationFrame);try{const[t]=await Promise.all([p(u,l),w(700)]);y(t.hits);const r=Math.ceil(f/15);l<r?b():d.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});const e=document.querySelector(".gallery li");if(e){const{height:i}=e.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}catch{d.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{L("bottom")}});
//# sourceMappingURL=index.js.map
